"""Add start and end fields to TaskModel

Revision ID: 4c666c2e2422
Revises: 63057bcb505e
Create Date: 2024-05-05 19:32:08.082182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c666c2e2422'
down_revision = '63057bcb505e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('end')
        batch_op.drop_column('start')

    # ### end Alembic commands ###
