"""added created_by column in tasks

Revision ID: 63057bcb505e
Revises: a4efa4f431ae
Create Date: 2024-04-11 16:04:27.021042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63057bcb505e'
down_revision = 'a4efa4f431ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
