"""renamed task attachment field description to info

Revision ID: d10ff62c0e54
Revises: 12cbbac0ce22
Create Date: 2024-05-14 11:45:42.973944

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd10ff62c0e54'
down_revision = '12cbbac0ce22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task-attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info', sa.String(length=255), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task-attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('info')

    # ### end Alembic commands ###
