"""Add first_name, last_name, and password fields to UserModel

Revision ID: 1af94a271f91
Revises: 7a422bc29a6c
Create Date: 2024-04-03 21:58:35.690585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1af94a271f91'
down_revision = '7a422bc29a6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=False))
        batch_op.alter_column('first_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('last_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('password')

    # ### end Alembic commands ###
