"""renamed task attachment field file_path to file

Revision ID: 3565bf70c5d8
Revises: d10ff62c0e54
Create Date: 2024-05-14 12:55:27.034078

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3565bf70c5d8'
down_revision = 'd10ff62c0e54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task-attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file', sa.String(length=255), nullable=True))
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task-attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('file')

    # ### end Alembic commands ###
